version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: consultant-tracker-mongodb-prod
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: consultant_tracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - consultant-tracker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: consultant-tracker-backend-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/consultant_tracker?authSource=admin
    depends_on:
      - mongodb
    networks:
      - consultant-tracker-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: consultant-tracker-frontend-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000/api}
    depends_on:
      - backend
    networks:
      - consultant-tracker-network
    command: npm start

volumes:
  mongodb_data:

networks:
  consultant-tracker-network:
    driver: bridge
